#!/usr/bin/python

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Read new and old password from a file, then check passwords against pwquality library.
#
# The file must contain the old password in the first line, and the new password in the second line
#

from __future__ import print_function
import pwquality
import sys
import os.path

def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)


if len (sys.argv) < 2:
    eprint("Usage: check-pwquality <file");
    sys.exit(1)

passfile = sys.argv[1]

if not os.path.isfile(passfile):
    eprint("No such file or directory: %s" % passfile);
    sys.exit(1)

# read file
fp = open(passfile, "r")
lines = fp.readlines()
old = lines[0];
new = lines[1]

# execute pwquality checkes
try:
    pw_quality = pwquality.PWQSettings()
    pw_quality.read_config()
    pw_quality.check(new, old, None)
except pwquality.PWQError as (e, msg):
    print(msg)
    sys.exit(1)

sys.exit(0)
