#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

. /usr/libexec/nethserver/api/lib/helper_functions

data=$(cat /dev/stdin)
action=$(echo $data | jq -r '.action')

function _get
{
    field=$1
    echo $data | jq -r ".$field"
}

id=$(id -u)
new_password="$(jq -r '.newPassword' <<<"${data}")"
confirm_password="$(jq -r '.confirmNewPassword' <<<"${data}")"
if [[ $new_password -ne $confirm_password ]]; then
    echo '{"id":1548426069,"type":"NotValid","message":"validation_failed","attributes":[{"parameter":"confirmNewPassword","value":null,"error":"passwords_dont_match"}]}'
    error
fi

if [[ $id -eq 0 ]]; then
    LANG=C /usr/libexec/nethserver/api/system-password/change-root-passwd >/dev/null <<<"$new_password"
else
    current_password="$(jq -r '.currentPassword' <<<"${data}")"
    LANG=C /usr/libexec/nethserver/api/system-password/change-user-passwd >/dev/null >/dev/null <<EOF
$current_password
$new_password
EOF
fi

if [[ $? -ne 0 ]]; then
    error
else
    success
fi


