#!/bin/bash

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

. /usr/libexec/nethserver/api/lib/helper_functions

data=$(cat /dev/stdin)

new_password="$(jq -r '.newPassword' <<<"${data}")"
confirm_password="$(jq -r '.confirmNewPassword' <<<"${data}")"
current_password="$(jq -r '.currentPassword' <<<"${data}")"

if [[ "${new_password}" != "${confirm_password}" ]]; then
    echo '{
        "id": 1548426069,
        "type": "NotValid",
        "message": "validation_failed",
        "attributes": [{
            "parameter": "confirmNewPassword",
            "value": null,
            "error": "passwords_dont_match"
        }]
    }'
    exit 1
fi

if [[ $(id -u) == 0 ]]; then
    /usr/libexec/nethserver/api/system-password/change-root-passwd 1>&2 <<<"$new_password"
else
    /usr/libexec/nethserver/api/system-password/change-user-passwd 1>&2 >/dev/null <<EOF
$current_password
$new_password
EOF
fi

exit_code=$?
if [[ $exit_code == 0 ]]; then
    success
elif [[ $exit_code == 1 ]]; then
    error
elif [[ $exit_code == 49 ]]; then
    error "AuthError" "invalid_credentials"
else
    error "UnknownError" "exit_code $exit_code"
fi


