#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

. /usr/libexec/nethserver/api/lib/helper_functions

data=$(cat /dev/stdin)
action=$(echo $data | jq -r '.action')

function _get
{
    field=$1
    echo $data | jq -r ".$field"
}

id=$(id -u)
pass_file=$(mktemp)
echo $data | jq -r ".newPassword" >> $pass_file
echo $data | jq -r ".confirmNewPassword" >> $pass_file
if [ $id -gt 0 ]; then
    echo $data | jq -r ".currentPassword" >> $pass_file
    timeout 3 /usr/libexec/nethserver/api/system-password/change-user-passwd $pass_file &>/dev/null
else
    timeout 3 /usr/libexec/nethserver/api/system-password/change-root-passwd $pass_file &>/dev/null
fi
tmp=$?
rm -f $pass_file

if [ $tmp -gt 0 ]; then
    error
else
    success
fi


