#!/usr/bin/php
<?php
/*
 * Copyright (C) 2018 Nethesis S.r.l.
 * http://www.nethesis.it - nethserver@nethesis.it
 *
 * This script is part of NethServer.
 *
 * NethServer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License,
 * or any later version.
 *
 * NethServer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with NethServer.  If not, see COPYING.
*/

require_once("/usr/libexec/nethserver/api/lib/Helpers.php");

$data = readInput();

$data['props']['name'] = $data['name'];
$v = new LegacyValidator($data['props']);

$v->declareParameter('name', Validate::HOSTNAME_FQDN);
$v->declareParameter('WildcardMode', Validate::SERVICESTATUS);
$v->declareParameter('IpAddress', Validate::IPv4);

$db = new EsmithDatabase('hosts');
$keyExists = $db->getType($data['name']) != '';
if ($data['action'] == 'create' && $keyExists) {
    $v->addValidationError('hostname', 'Service_key_exists_message');
}

# Validate the input
if ($v->validate()) {
    success();
} else {
    error($v);
}

