#!/usr/bin/perl
#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use esmith::Build::CreateLinks  qw(:all);


#
# nethserver-cockpit-update event
#

event_actions('nethserver-cockpit-update', qw(
      initialize-default-databases   00
      nethserver-cockpit-conf        20
      nethserver-cockpit_update_admins_group 10
));

event_templates('nethserver-cockpit-update', qw(
    /etc/os-release
    /etc/cockpit/ws-certs.d/99-nethserver.cert
    /usr/share/cockpit/nethserver/manifest.json
    /etc/nethserver/ldappasswd.conf
    /etc/sudoers.d/30_nethserver_cockpit_roles
    /etc/sudoers.d/50_servermanager_perms
    /etc/shells
));

#
# certificate-update event
#

event_templates('certificate-update', qw(
    /etc/cockpit/ws-certs.d/99-nethserver.cert
));

event_actions('certificate-update', qw(
      nethserver-cockpit-conf        20
));

#
# nethserver-subscription-save
#

event_templates('nethserver-subscription-save', qw(
   /etc/os-release
));

#
# nethserver-sssd-save event
#
event_templates('nethserver-sssd-save', qw(
    /etc/nethserver/ldappasswd.conf
));

#
#  delegation-save
#
event_templates('delegation-save', qw(
    /etc/sudoers.d/50_servermanager_perms
));

#
# runlevel-adjust
#
event_templates('runlevel-adjust', qw(
    /etc/sudoers.d/50_servermanager_perms
));

event_actions('delegation-save', qw(
      nethserver-cockpit_update_admins_group 10
));
#
# Test events for development
#

safe_symlink('/bin/true', 'root/etc/e-smith/events/test-success/S20true');
safe_symlink('/bin/false', 'root/etc/e-smith/events/test-failure/S20false');
safe_symlink('/bin/true', 'root/etc/e-smith/validators/test-success/S20true');
safe_symlink('/bin/false', 'root/etc/e-smith/validators/test-failure/S20false');
