#!/bin/bash

# Prepare source for RPM build
# Check for js utils: npm

set -e

which npm >/dev/null

if [ $? -gt 1 ]; then
    echo "[ERROR] Install 'npm' package: 'yum/dnf install npm'"
    exit 1
fi

# Cleanup existing release
rm -rf ui/dist/
rm -rf ui/*.tar.gz
rm -f *.tar.gz
rm -f *.rpm
rm -f *.log

# Pull new languages strings if .pot exists.


# Install dependecies and build UI
pushd ui && ./prep-sources && cd dist && tar cvzf ../../nethserver-cockpit-ui.tar.gz *
popd
