#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Functions for BASH helpers
#

#
# Print an InvalidInput error and exit 1
#
function invalid_error {
        error "InvalidInput" "No JSON data available"
}

#
# Print a JSON error and exit 1
# Takes 2 arguments:
#   - the error type (default: GenericError)
#   - a message (default "Generic error")
#
function error {
    type=${1:-"GenericError"}
    message=${2-"Generic error"}

    printf '{"id":"%s","type":"%s","message":"%s"}' "$(date +%s)" "$type" "$message"
    exit 1
}

#
# Print a success JSON object and exit 0
#
function success {
    printf '{"state":"success"}'
    exit 0
}

