#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use warnings;
use strict;
use JSON;
use esmith::ConfigDB;

my $db = esmith::ConfigDB->open_ro();
my $ps = $db->get('passwordstrength');
my %props = $ps->props;
delete $props{'type'};
delete $props{'PassWarning'};
if ($props{'Users'} eq 'none') {
    $props{'Users'} = 'no';
} else {
    $props{'Users'} = 'yes';
}

print encode_json({'configuration' => { 'name' => $ps->key, 'type' => 'configuration', 'props' => \%props }, 'status' => ''}); 
