#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

. /usr/libexec/nethserver/api/lib/helper_functions

data=$(cat /dev/stdin)

function _get
{
    field=$1
    echo $data | jq -r ".props.$field"
}

users=$(_get Users)
if [ "$users" == "yes" ]; then
    users="strong"
else
    users="none"
fi

# Read JSON from stdin and set the record
/sbin/e-smith/config setprop passwordstrength PassExpires $(_get PassExpires) MinPassAge $(_get MinPassAge)  MaxPassAge $(_get MaxPassAge) Users $users 

if [ $? -gt 0 ]; then
    invalid_error
fi

/sbin/e-smith/signal-event -j password-policy-update
if [ $? -gt 0 ]; then
    error "EventFailed" "See /var/log/messages"
else
    success
fi
