#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Return current ssh connections and sshd configuration
#

use strict;
use warnings;
use JSON;
use esmith::ConfigDB;
use esmith::db;
my $db = esmith::db->open("configuration");
my $port = $db->get_prop('chronyd', 'TCPPort');
my $time = `date`;
chomp $time;
my $chronyd = $db->prepare_json('chronyd');

# Use ConfigDB to access the config via DBUS 
my $db2 = esmith::ConfigDB->open_ro(); 
my $timezone = $db2->get('TimeZone');

open(DATE, "timedatectl list-timezones|");
my @timezones = <DATE>;
close(DATE);
chomp @timezones;

my %out = (
    'status' => { 'time' => $time },
    'configuration' => { 'chronyd' => $chronyd, 'timezones' => \@timezones, 'timezone' =>  $timezone->prop('type') }
);
print to_json(\%out, {utf8 => 1, pretty => 0, allow_nonref => 1});
