#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

require "/usr/libexec/nethserver/api/lib/helper_functions.pl";

use warnings;
use strict;

my $input = readInput();
my $cmd = $input->{'action'};
my $lines = $input->{'lines'} || '50';

sub dump_logs
{
    my $paths = shift;
    my $lines = shift;
    my $mode = shift;
    my $follow = shift;
    my $cmd = '';
    my $args = '';

    if ($mode eq 'systemd') {
        $cmd .= "journalctl ";
        $args = " -u ".join(" -u ",@$paths);
    } else {
        $cmd .= "tail ";
        $args = join(" ",@$paths);
    }
    if ($follow) {
        $cmd .= " -f ";
    } else {
        $cmd .= " -n $lines";
    }
    system("$cmd $args"); 
}


if($cmd eq 'follow') {
    dump_logs($input->{'paths'}, $lines, $input->{'mode'}, 1);
} elsif ($cmd eq 'dump') {
    dump_logs($input->{'paths'}, $lines, $input->{'mode'}, 0);
} else {
    error();
}
