#!/usr/bin/perl

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use NethServer::ApiTools qw(hints success error readInput safe_decode_json invoke_info_api);
use strict;
use warnings;

use esmith::ConfigDB;
use JSON;

my $db = esmith::ConfigDB->open_ro();
my $details;

my $port = $db->get_prop('sshd','TCPPort');
my $StrongEncryption = $db->get_prop('sshd','StrongEncryption');

if ($port == 22){
    $details->{'TCPPort'} = 'change_default_ssh_port';
}

if ( $StrongEncryption eq 'disabled') {
    $details->{'StrongEncryption'} = 'change_default_ssh_encryption';
}

if ($details) {
    hints(undef,$details);
} else {
    hints();
}
