#!/usr/bin/perl

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::ConfigDB;
use esmith::event;
use JSON;
use NethServer::ApiTools;
my $data = NethServer::ApiTools::readInput();
my $cdb = esmith::ConfigDB->open()|| NethServer::ApiTools::error("EventError", "Cannot_open_esmith_configuration");
my $action = $data->{'action'};

foreach my $prop (qw(
    PasswordAuthentication
    PermitRootLogin
    TCPPort
    AllowEveryone
    )) {
        $cdb->set_prop('sshd', $prop, $data->{'props'}{$prop});
    }

my $AllowGroups = '';
foreach my $g (keys $data->{'props'}{'AllowGroups'} ) {
    if ($data->{'props'}{'AllowGroups'}{$g} eq 'ssh') {
        $AllowGroups .= "$g,";
    } elsif ($data->{'props'}{'AllowGroups'}{$g} eq 'sftp') {
        $AllowGroups .= "$g:sftp,";
    }
} 
chop $AllowGroups;
$cdb->set_prop('sshd', 'AllowGroups', $AllowGroups);

esmith::event::set_json_log(1);
my $success = esmith::event::event_signal('nethserver-openssh-save');
if($success) {
    NethServer::ApiTools::success();
} else {
   NethServer::ApiTools::error("EventError", "update_action_failed", 15507635545762);
}
