#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

HOST=$1
DIR=$2

exit_code=1
tmp_dir=$(mktemp -d)
tmp_file=$(mktemp -u -p $tmp_dir)

timeout 5 mount $HOST:$DIR $tmp_dir
exit_code=$?
if [ $exit_code == 0 ]; then
    touch  $tmp_file
    exit_code=$?
fi

# preserve exit code using $exit_code
trap "{ rm -f $tmp_file; umount $tmp_dir 2>/dev/null; rmdir $tmp_dir 2>/dev/null; exit $exit_code; }" EXIT SIGINT SIGTERM

