#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

. /usr/libexec/nethserver/api/lib/helper_functions

data=$(cat /dev/stdin)
action=$(echo $data | jq -r '.action')

function _get
{
    field=$1
    echo $data | jq -r ".$field"
}


case $action in

    "backup-config")
        /usr/libexec/nethserver/backup-config-history drop -i "$(_get name)"
        ;;

    "backup-data")
        /sbin/e-smith/db backups delete "$(_get name)"
        /sbin/e-smith/signal-event -j nethserver-backup-data-save
        ;;

esac

if [ $? -gt 0 ]; then
    error "EventFailed" "See /var/log/messages"
else
    success
fi
