#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

. /usr/libexec/nethserver/api/lib/helper_functions

data=$(cat /dev/stdin)
action=$(echo $data | jq -r '.action')

function _get
{
    field=$1
    echo $data | jq -r ".$field"
}


case $action in

    "format-disk")
        /usr/libexec/nethserver/api/system-backup/format-disk "$(_get name)"
        ;;

    "run-backup-data")
        unit=cockpit-backup-data-"$(_get name)"

        # Skip double execution
        systemctl is-active $name >/dev/null
        if [ $? -eq 0 ]; then
            exit 0
        else
            systemctl reset-failed $name >/dev/null
        fi

        systemd-run --unit=cockpit-backup-data-"$(_get name)" /sbin/e-smith/backup-data-wrapper "$(_get name)"
        ;;

    "run-backup-config")
        /usr/libexec/nethserver/backup-config-history push -t snapshot -d "$(_get name)"
        ;;

    "download-backup-config")
        tmp=$(mktemp)
        # the file must be inside /tmp and must already exists
        /usr/libexec/nethserver/backup-config-history pull -i "$(_get name)" -f $tmp
        cat $tmp | base64 -w 0
        rm -f $tmp
        ;;

esac
