#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use esmith::ConfigDB;
use NethServer::BackupData;
use JSON;

require '/usr/libexec/nethserver/api/lib/helper_functions.pl';

my $db = esmith::ConfigDB->open_ro('backups');
foreach my $b ($db->get_all()) {
    my $status = $b->prop('status');
    if ($status eq 'enabled') {
        hints();
    }
}
hints('must_configure_backup_data', undef, 'http://docs.nethserver.org/en/v7/backup.html');
