#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use esmith::ConfigDB;

require '/usr/libexec/nethserver/api/lib/backup_functions.pl';

my $input = readInput();

my $cmd = $input->{'action'};
delete($input->{'action'});

if($cmd eq 'update-backup-data') {
    set_backup($input);
} elsif($cmd eq 'update-backup-config') {
    my $db = esmith::ConfigDB->open();
    $db->set_prop('backup-config', 'HistoryLength', $input->{'HistoryLength'});
    my $out = `/usr/libexec/nethserver/backup-config-history drop -e`; # grab the output in case of unwanted errors
    if ($? > 0) {
        error();
    } else {
        success();
    }

} else {
    error();
}
