#!/usr/bin/php
<?php
/*
 * Copyright (C) 2018 Nethesis S.r.l.
 * http://www.nethesis.it - nethserver@nethesis.it
 *
 * This script is part of NethServer.
 *
 * NethServer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License,
 * or any later version.
 *
 * NethServer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with NethServer.  If not, see COPYING.
*/

require_once("/usr/libexec/nethserver/api/lib/dhcp_functions.php");

$vfstypes = array('usb','cifs','nfs','b2','s3','sftp','webdav');
$engines = array('duplicity','restic','rsync');
$cleanuptypes = array('never','1D','7D','14D','28D','56D','168D','364D');

function validate_time($time, &$error)
{
    $time = trim($time);
    if (!@$time) {
        $error = 'backuptime_not_found';
        return false;
    }
    $tmp = explode(" ",$time);
    if (count($tmp) < 5) {
        $error = "backuptime_not_enough_elements";
        return false;
    }

    return true;
}

function fail($parameter, $error)
{
    $error = array(
        "id" => time(),
        "type" => 'NotValid',
        "message" => "validation_failed",
        "attributes" => array(array("parameter" => $parameter, "value" => '', "error" => $error))
    );

    echo json_encode($error);
    exit(1);

}

function find_role($db, $interface) {
    $i = $db->getKey($interface);
    $role = @$i['role'];
    if ($role == 'bridged') {
        $role = $db->getProp($i['bridge'], 'role');
    }
    if ($role == 'slave') {
        $role = $db->getProp($i['master'], 'role');
    }

    return $role;
}

$data = readInput();
$action = $data['action'];


$v = new LegacyValidator($data);
if ($action == 'create-backup-data' || $action == 'update-backup-data') {
    $v->declareParameter('name', Validate::USERNAME);
    $v->declareParameter('status', Validate::SERVICESTATUS);
    $v->declareParameter('VFSType', $v->createValidator()->memberOf($vfstypes));
    $v->declareParameter('engine', $v->createValidator()->memberOf($engines));
    $v->declareParameter('Notify',  $v->createValidator()->memberOf(array('error','always','never')));
    $v->declareParameter('IncludeLogs', Validate::SERVICESTATUS);
    $v->declareParameter('CleanupOlderThan', $v->createValidator()->memberOf($cleanuptypes));

    $db = new EsmithDatabase('backups');
    $r = $db->getKey($data['name']);
    if ($r && $action == 'create-backup-data') {
        $v->addValidationError('name','backup_already_exists');
        error($v);
    };

    if (!validate_time($data['BackupTime'], $error)) {
        $v->addValidationError('BackupTime',$error);
        error($v);
    }


    switch($data['engine']) {
    case 'duplicity':
        $v->declareParameter('Type', $v->createValidator()->memberOf(array('full','incremental')));
        $v->declareParameter('FullDay', $v->createValidator()->integer()->greatThan(-1)->lessThan(7));
        $v->declareParameter('VolSize', $v->createValidator()->integer()->greatThan(1));
        break;
    case 'restic':
        $v->declareParameter('Prune', $v->createValidator()->memberOf(array('always',0,1,2,3,4,5,6,7)));
        break;
    }
    switch($data['VFSType']) {
    case 'usb':
        $v->declareParameter('USBLabel', Validate::NOTEMPTY);
        break;
    case 'cifs':
        $v->declareParameter('SMBShare', Validate::NOTEMPTY);
        $v->declareParameter('SMBHost', Validate::HOSTADDRESS);
        $v->declareParameter('SMBLogin', Validate::ANYTHING);
        $v->declareParameter('SMBPassword', Validate::ANYTHING);
        break;
    case 'nfs':
        $v->declareParameter('NFSShare', Validate::NOTEMPTY);
        $v->declareParameter('NFSHost', Validate::HOSTADDRESS);
        break;
    case 'sftp':
        $v->declareParameter('SftpHost', Validate::HOSTADDRESS);
        $v->declareParameter('SftpPort', Validate::PORTNUMBER);
        $v->declareParameter('SftpUser', Validate::NOTEMPTY);
        $v->declareParameter('SftpPassword', Validate::NOTEMPTY);
        $v->declareParameter('SftpDirectory', Validate::NOTEMPTY);
        break;
    case 's3':
        $v->declareParameter('S3AccessKey', Validate::NOTEMPTY);
        $v->declareParameter('S3Bucket', Validate::NOTEMPTY);
        $v->declareParameter('S3SecretKey', Validate::NOTEMPTY);
        $v->declareParameter('S3Host', Validate::HOSTADDRESS);
        break;
    case 'b2':
        $v->declareParameter('B2AccountId', Validate::NOTEMPTY);
        $v->declareParameter('B2AccountKey', Validate::NOTEMPTY);
        $v->declareParameter('B2Bucket', Validate::NOTEMPTY);
        break;
    case 'webdav':
        $v->declareParameter('WebDAVUrl', Validate::NOTEMPTY);
        $v->declareParameter('WebDAVLogin', Validate::ANYTHING);
        $v->declareParameter('WebDAVPassword', Validate::ANYTHING);
    }

} else if ($action == 'sftp-credentials') {
    $pass_file = tempnam("/tmp","SFTP");
    file_put_contents($pass_file, $data['SftpPassword']);
    exec("/usr/libexec/nethserver/api/system-backup/check-sftp {$data['SftpHost']} {$data['SftpPort']} {$data['SftpUser']} {$data['SftpDirectory']} $pass_file", $output, $ret);
    unlink($pass_file);
    if ($ret > 0) {
        fail('SftpHost', 'sftp_invalid_credentials');
    } else {
        success();
    }

} else if ($action == 'b2-credentials') {
    exec("/usr/libexec/nethserver/api/system-backup/check-b2 {$data['B2AccountId']} {$data['B2AccountKey']} {$data['B2Bucket']}", $output, $ret);
    $errors = array(
        "1" => "b2_unauthorized",
        "2" => "b2_bucket_not_found",
        "3" => "b2_upload failed",
        "4" => "b2_delete_failed"
    );
    if ($ret > 0) {
        if ($ret == 1 ) {
            $param = "B2AccountId";
        } else {
            $param = "B2Bucket";
        }
        fail($param, $errors["$ret"]);
    } else {
        success();
    }

} else if ($action == 's3-credentials') {
    exec("/usr/libexec/nethserver/api/system-backup/check-s3 {$data['S3AccessKey']} {$data['S3SecretKey']} {$data['S3Bucket']} {$data['S3Host']}", $output, $ret);
    if ($ret > 0) {
        fail("S3Bucket","s3_unauthorized");
    } else {
        success();
    }

} else if ($action == 'nfs-credentials') {
    exec("/usr/libexec/nethserver/api/system-backup/check-nfs {$data['NFSHost']} {$data['NFSShare']}", $output, $ret);
    if ($ret > 0) {
        fail("NFSHost","nfs_unauthorized");
    } else {
        success();
    }

} else if ($action == 'cifs-credentials') {
    $pass_file = tempnam("/tmp","SMB");
    file_put_contents($pass_file, "username={$data['SMBLogin']}\npassword={$data['SMBPassword']}\n");
    exec("/usr/libexec/nethserver/api/system-backup/check-cifs {$data['SMBHost']} $pass_file {$data['SMBShare']}", $output, $ret);
    unlink($pass_file);
    if ($ret > 0) {
        fail("SMBHost","cifs_unauthorized");
    } else {
        success();
    }
} else if ($action == 'webdav-credentials') {
    $pass_file = tempnam("/tmp","WEBDAV");
    file_put_contents($pass_file, $data['WebDAVPassword']);
    exec("/usr/libexec/nethserver/api/system-backup/check-webdav ".escapeshellarg($data['WebDAVUrl'])." ".escapeshellarg($data['WebDAVLogin'])." $pass_file", $output, $ret);
    unlink($pass_file);
    if ($ret > 0) {
        fail("WebDAVUrl","webdav_unauthorized");
    } else {
        success();
    }

} else if ($action == 'disk-access') {
    exec("/usr/libexec/nethserver/api/system-backup/check-disk {$data['USBLabel']}", $output, $ret);
    $errors = array(
        "1" => "usb_filesystem_not_found",
        "2" => "usb_mount_failed",
        "3" => "usb_write_failed",
        "4" => "usb_delete_failed"
    );
    if ($ret > 0) {
        fail($data['USBLabel'], $errors["$ret"]);
        error(array("type" => "NotValid", "message" => "Disk access failed"));
    } else {
        success();
    }

} else if ($action == 'restore-backup-config') {

    # Pull the backup from history to a temporary file
    $tmp = tempnam(sys_get_temp_dir(), 'restore-config-validation');
    $tmp_dir = sys_get_temp_dir()."/restore-config-tmp";
    $tmp_db = $tmp_dir."/var/lib/nethserver/db/networks";
    @mkdir($tmp_dir);
    exec("/usr/libexec/nethserver/backup-config-history pull -f $tmp -i ".$data['data']);
    exec("tar xf $tmp -C $tmp_dir var/lib/nethserver/db/networks");

    $green_found = false;
    $ndb = new EsmithDatabase($tmp_db);
    foreach ($data['remap'] as $dest=>$cur) {
        if (find_role($ndb, $dest) == 'green') {
            $green_found = true;
        }
    }
    if (!$green_found) {
        $v->addValidationError('remap','remap_at_least_one_green');
    }

    exec("/usr/libexec/nethserver/restore-config-check-registration $tmp", $out, $ret);
    if ($ret > 0) {
        $v->addValidationError('data','register_before_restore');
    }

    unlink($tmp);
    exec("rm -rf $tmp_dir");

} else {
    error();
}

# Validate the input
if ($v->validate()) {
    success();
} else {
    error($v);
}

