#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

. /usr/libexec/nethserver/api/lib/helper_functions

data=$(cat /dev/stdin)
action=$(echo $data | jq -r '.action')

function _get
{
    field=$1
    echo $data | jq -r ".$field"
}


case $action in

    "update-reservation")
        /sbin/e-smith/db hosts set "$(_get name)" local IpAddress "$(_get IpAddress)" MacAddress "$(_get MacAddress)" Description "$(_get Description)"
        if [ $? -gt 0 ]; then
            error "EventFailed" "See /var/log/messages"
        fi
        /sbin/e-smith/signal-event -j host-modify
        ;;

    "update-range")
        /sbin/e-smith/db dhcp set "$(_get name)" range status "$(_get status)" DhcpRangeStart "$(_get DhcpRangeStart)" DhcpRangeEnd "$(_get DhcpRangeEnd)" DhcpGatewayIP "$(_get DhcpGatewayIP)" \
            DhcpLeaseTime "$(_get DhcpLeaseTime)" DhcpDomain "$(_get DhcpDomain)" DhcpDNS "$(_get DhcpDNS)" DhcpWINS "$(_get DhcpWINS)" DhcpNTP "$(_get DhcpNTP)" DhcpTFTP "$(_get DhcpTFTP)"
        if [ $? -gt 0 ]; then
            error "EventFailed" "See /var/log/messages"
        else
            success
        fi
        /sbin/e-smith/signal-event -j nethserver-dnsmasq-save
        ;;
esac

if [ $? -gt 0 ]; then
    error "EventFailed" "See /var/log/messages"
else
    success
fi
