#!/usr/bin/php
<?php
/*
 * Copyright (C) 2018 Nethesis S.r.l.
 * http://www.nethesis.it - nethserver@nethesis.it
 *
 * This script is part of NethServer.
 *
 * NethServer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License,
 * or any later version.
 *
 * NethServer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with NethServer.  If not, see COPYING.
*/


require_once("/usr/libexec/nethserver/api/lib/Helpers.php");

$data = readInput();

$v = new LegacyValidator($data['props']);

$vh = $v->createValidator()->orValidator($v->createValidator(Validate::HOSTNAME), $v->createValidator(Validate::EMPTYSTRING));
$vp = $v->createValidator()->orValidator($v->createValidator(Validate::PORTNUMBER), $v->createValidator(Validate::EMPTYSTRING));
$v->declareParameter('host', $vh);
$v->declareParameter('port', $vp);
$v->declareParameter('username', Validate::ANYTHING);
$v->declareParameter('password', Validate::ANYTHING);


# Validate the input
if ($v->validate()) {
    success();
} else {
    error($v);
}
