#!/usr/bin/python

import sys
import os
import glob
import json

path = '/usr/share/cockpit/nethserver/applications/'

applications = []

if len(sys.argv) > 1:
    fullpath = os.path.join(path, sys.argv[1] + '.json')
    with open(fullpath) as data_file:
        try:
            data = json.load(data_file)
            print json.dumps(data)
        except:
            pass

else:
    for filename in glob.glob(path + '*.json'):

        fullpath = os.path.join(path, filename)
        with open(fullpath) as data_file:
            try:
                data = json.load(data_file)
                applications.append(data)
            except:
                pass

    print json.dumps(applications)
