#!/usr/bin/python

import sys
import os
import glob
import json

path = '/usr/share/cockpit/nethserver/applications/'
applications = []

def list_all():
    for filename in glob.glob(path + '*.json'):
        fullpath = os.path.join(path, filename)
        with open(fullpath) as data_file:
            try:
                data = json.load(data_file)
                applications.append(data)
            except:
                pass

    print json.dumps(applications)


if not sys.stdin.isatty():
    data = json.load(sys.stdin)
    if data and data["name"]:
        fullpath = os.path.join(path, data["name"] + '.json')
        with open(fullpath) as data_file:
            try:
                data = json.load(data_file)
                print json.dumps(data)
            except:
                pass
    else:
        list_all()

else:
    list_all()
