#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;

require '/usr/libexec/nethserver/api/lib/helper_functions.pl';
require '/usr/libexec/nethserver/api/lib/auth_functions.pl';

my $input = readInput();
my $cmd = $input->{'action'};
my $name = $input->{'name'};
my $user = whoami();
my $isAdmin = isAdmin($user);

# root can always access everything
if (($user eq 'root') ||
        ( $isAdmin == 1)) {
    success();
}

my $acl = get_acl($user);

if ($cmd eq 'check-app') {
    foreach my $i (@{$acl->{'applications'}}) {
        if ($i eq $name) {
            success();
        }
    }
} elsif ($cmd eq 'check-system') {
    foreach my $i (@{$acl->{'system'}}) {
        if ($i eq $name) {
            success();
        }
    }
}
error("NotValid","permission_denied");
