#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

. /usr/libexec/nethserver/api/lib/helper_functions

app=$(jq -r .name)

# Check if the current user is either root or an admin, or is delegated to use $app
/usr/libexec/nethserver/api/system-authorization/read  | \
    jq -e --arg app "${app}" 'if (.status.isRoot == 1 or .status.isAdmin == 1 or (.applications | index($app)) >= 0) then 1 else null end' >/dev/null

if [[ $? == 0 ]]; then
    success
else
    error "NotAuthorized" "The application $app is not authorized for the current user"
fi
