#!/usr/bin/php
<?php

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

require_once("/usr/libexec/nethserver/api/lib/Helpers.php");

$data = readInput();

$params = $data['chronyd']['props'];
$params['date'] = $data['date'];
$params['time'] = $data['time'];
$params['timezone'] = $data['timezone'];
$v = new LegacyValidator($params);

$timezones = explode("\n",shell_exec('timedatectl list-timezones'));
$timezones = array_filter($timezones); # remove empty elements

$v->declareParameter('status', Validate::SERVICESTATUS);
$v->declareParameter('date', Validate::DATE);
$v->declareParameter('time', Validate::TIME);
$v->declareParameter('NTPServer', Validate::HOSTNAME);
$v->declareParameter('timezone', $v->createValidator()->memberOf($timezones));

if ($v->validate()) {
    success();
} else {
    error($v);
}
