#!/usr/bin/php
<?php

/*
 * Copyright (C) 2018 Nethesis S.r.l.
 * http://www.nethesis.it - nethserver@nethesis.it
 *
 * This script is part of NethServer.
 *
 * NethServer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License,
 * or any later version.
 *
 * NethServer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with NethServer.  If not, see COPYING.
 */

require_once("/usr/libexec/nethserver/api/lib/Helpers.php");

define("LINK_BASE_URL","https://docs.nethserver.org");
define("VERSION","latest");

function get_link($chapter, $lang, $section)
{
    return LINK_BASE_URL."/$lang/".VERSION."/$chapter.html#$section";
}


$data = readInput();

$link = get_link($data['chapter'], $data['language'], $data['section']);

echo json_encode(array("link" => $link));
