#!/usr/bin/php
<?php

/*
 * Copyright (C) 2018 Nethesis S.r.l.
 * http://www.nethesis.it - nethserver@nethesis.it
 *
 * This script is part of NethServer.
 *
 * NethServer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License,
 * or any later version.
 *
 * NethServer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with NethServer.  If not, see COPYING.
 */

require_once("/usr/libexec/nethserver/api/lib/Helpers.php");

define("DOWNLOAD_BASE_URL","http://docs.nethserver.org");
define("LINK_BASE_URL","http://docs.nethserver.org");
define("VERSION","latest");

function get_link($chapter, $lang, $section)
{
    return LINK_BASE_URL."/$lang/".VERSION."/$chapter.html#$section";
}

function get_download_url($chapter, $lang)
{
    return DOWNLOAD_BASE_URL."/$lang/".VERSION."/$chapter.html#";
}

function find_section($url, $section)
{
    $ret = '';
    $html = @file_get_contents($url);
    if ($html) {
        $dom = new DOMDocument;
        @$dom->loadHTML($html);
        $doc = simplexml_import_dom($dom);

        $elements = $doc->xpath("//div[contains(@class, '$section')]");
        if ($elements && $elements[0]) {
            # remove class attributes before returning
            return preg_replace("/class=\".*\"/", "", $elements[0]->asXML());
        }
    }
    return $ret;
}

$data = readInput();

$url = get_download_url($data['chapter'], $data['language']);
$link = get_link($data['chapter'], $data['language'], $data['section']);
$html = find_section($url, $data['section']);

echo json_encode(array("data" => base64_encode($html), "link" => $link));
