#!/usr/bin/php
<?php

/*
 * Copyright (C) 2018 Nethesis S.r.l.
 * http://www.nethesis.it - nethserver@nethesis.it
 *
 * This script is part of NethServer.
 *
 * NethServer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License,
 * or any later version.
 *
 * NethServer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with NethServer.  If not, see COPYING.
 */

require_once("/usr/libexec/nethserver/api/lib/Helpers.php");

define("BASE_URL","https://nethserver-docs-cockpit.readthedocs.io");
define("VERSION","latest");
define("CACHE_DIR","/var/spool/nethserver-cockpit/docs");

function get_url($chapter, $lang)
{
    return BASE_URL."/$lang/".VERSION."/$chapter.html";
}

function find_section($url, $section)
{
    $ret = '';
    $html = @file_get_contents($url);
    if ($html) {
        $dom = new DOMDocument;
        @$dom->loadHTML($html);
        $el = $dom->getElementById($section);
        if ($el) {
            return $dom->saveHTML($el);
        }
    }
    return $ret;
}

$data = readInput();

$url = get_url($data['chapter'], $data['language']);
$html = find_section($url, $data['section']);

echo json_encode(array("data" => base64_encode($html), "link" => $url));
