#!/usr/bin/php
<?php

require_once("/usr/libexec/nethserver/api/lib/Helpers.php");

$data = readInput();

$v = new LegacyValidator($data);

$v->declareParameter('hostname', $v->createValidator()->hostname(2)->platform('myhostname'));

if ($v->validate()) {
    success();
} else {
    error($v);
}

