#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

policy=$(/sbin/e-smith/config getprop tls policy)

# Map empty value to 0
if [ -z $policy ]; then
    policy=0
else
    policy="\"$policy\""
fi
printf '{"status":{"available": ["20180621","20180330","20181001","20200510"]},"configuration":{"props":{"policy":%s},"name":"tls","type":"configuration"}}' "$policy"
