#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::ConfigDB;
use esmith::event;
use NethServer::ApiTools qw(readInput error success);

my $db = esmith::ConfigDB->open();
my $delegations = $db->get_prop('cockpit.socket','delegation')|| '';

my $input = readInput();
my $role = $input->{'role'} || '';
my $groupAdmins = $db->get_prop('admins','group');

my @system = @{$input->{'system'}}; 
my @applications = @{$input->{'applications'}};
my @permissions = ();
push @permissions,(@system,@applications);
my $values = '';

if ($role ne '') {

    if ($role ne  $groupAdmins) {
        #Update to cockpit.socket/delegation
        if ($delegations !~ /,$role:|^$role:/) {
            # search and if it doesn't exist, push it to values
            $values .=  $role .':'. join(':',@permissions).','.$delegations;
        } else {
            my @Keys = split(',', $delegations);
            foreach (@Keys) {
                my @props = split(':',$_);
                if ($props[0] eq $role) { # bingo we find the values to update
                    $values .= $role .':'. join(':',@permissions) .',';
                } else { # this value is not the one to update, push it to values
                   $values .= $_.',';
                }
            }
        }
        $values =~ s/,$//;
        $db->set_prop('cockpit.socket','delegation', $values); 
        if(esmith::event::event_signal('delegation-save')) {
            success();
        } else {
               error("EventError", "delegation-save failed update");
        }
    }

} else {
   error('NotValidAction','The action value is not valid');
}