#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

require "/usr/libexec/nethserver/api/lib/helper_functions.pl";
require "/usr/libexec/nethserver/api/lib/auth_functions.pl";

use warnings;
use strict;
use JSON;

my $jsonFile = '/etc/nethserver/cockpit/authorization/roles.json';
my $input = readInput();
my $role = $input->{'role'} || '';

my $data = read_json ($jsonFile); 

if ($role ne '') {
    $data->{$role}->{'system'} = $input->{'system'};
    $data->{$role}->{'applications'} = $input->{'applications'};

    write_json ($jsonFile,$data);

    my $out = `/sbin/e-smith/expand-template /etc/sudoers.d/30nethserver_cockpit_roles`;

    if ($? > 0) {
        error("EventFailed", "");
    } else {
        success();
    }
} else {
   error('NotValidAction','The action value is not valid');
}
