#!/usr/bin/php
<?php
#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

/** Include common functions **/

require_once("/usr/libexec/nethserver/api/system-users/functions.php");

$data = readInput();

function user_create($data) {
    $ret = 0;
    $tmp_ret = 0;
    passthru("/sbin/e-smith/signal-event -j user-create '{$data['name']}' ".escapeshellarg($data['gecos'])." {$data['shell']}", $tmp_ret);
    $ret += $tmp_ret;
    $ret += add_to_groups($data['name'], $data['groups']);
    passthru("/sbin/e-smith/signal-event -j password-policy-update '{$data['name']}' '{$data['expires']}'", $tmp_ret);
    $ret += $tmp_ret;
    $ret += save_password($data);
    exit($ret);
}

function group_create($data) {
    $cmd = "/sbin/e-smith/signal-event -j group-create '{$data['name']}'";
    foreach($data['members'] as $m) {
        $cmd .= " ".escapeshellarg($m);
    }

    passthru($cmd, $ret);
    exit($ret);
}

if ($data['action'] == 'user-create') {
    user_create($data);
} else if ($data['action'] == 'group-create') {
    group_create($data);
}
