#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use esmith::ConfigDB;
use JSON;
use POSIX qw/ceil/;

require '/usr/libexec/nethserver/api/lib/helper_functions.pl';

my $input = readInput();

my $cmd = $input->{'action'};

if ($cmd eq 'list-users') {
    my $db = esmith::ConfigDB->open_ro();
    my $provider = $db->get_prop('sssd', 'Provider') || '';
    my $out = `/usr/libexec/nethserver/list-users -s`;
    if ($provider eq 'ad') {
        my $users = safe_decode_json($out);
        open(FH, "LANG=C net ads search '(objectCategory=User)' name lastLogon|");
        my $user = '';
        while (<FH>) {
            next if /^\s*$/;    # skip blank lines
            if (/^name/) {
                my ($field,$value) = split;
                $user = $value;
            }
            if (/^lastLogon/) {
                chomp;
                $_ =~ s/^(.*:)//;
                my $lastLogon = ceil((int($_)/10000000)-11644473600);
                if ($users->{$user}) {
                    $users->{$user}{'lastLogon'} = $lastLogon > 0 ? $lastLogon : 0 ;
                }
                $user = '';
            }
        }
        close(FH);

        print encode_json($users);
    } else {
        print $out;
    }
} elsif ($cmd eq 'list-groups') {
    system("/usr/libexec/nethserver/list-groups -s");
} elsif ($cmd eq 'user-membership') {
    system("/usr/libexec/nethserver/list-user-membership -s '".$input->{'user'}."'");
} elsif ($cmd eq 'group-members') {
    system("/usr/libexec/nethserver/list-group-members -s '".$input->{'group'}."'");
}
