#!/bin/bash

# Prepare source for RPM build
# Check for js utils: npm

set -e

which npm >/dev/null

if [ $? -gt 1 ]; then
    echo "[ERROR] Install 'npm' package: 'yum/dnf install npm'"
    exit 1
fi

# Cleanup existing release
rm -rf dist/
rm -f *.tar.gz
rm -f *.rpm
rm -f *.log


# Install dependecies and build UI and API
npm install && npm run build
