#!/usr/bin/expect -f

#
# Expect a file in the format containing: the new and confirm password
# The password must be one per line.
#

set pass_file [lindex $argv 0]
set fp [open $pass_file r]
gets $fp new_pass
gets $fp confirm_pass

spawn passwd

expect  "ew password: "
send -- "$new_pass\n"
expect  "etype new password: "
send -- "$confirm_pass\n"
expect eof

set exitstatus [lindex [wait] 3]
