#!/usr/bin/python

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# Check if the root password is set to the default one
# Exit 1 if the password is the default one, exit 0 otherwise

import crypt
import sys

default_password="Nethesis,1234"

for line in open("/etc/shadow"):
    tmp = line.split(':')
    if tmp[0] == "root":
        # get full hash from second field
        # tmp[1] is the current hash
        h = tmp[1].split('$')

        # h[1] is the alghoritm
        # h[2] is the salt
        # h[3] is the hash
       
        default_hash = crypt.crypt(default_password, '$%s$%s$' % (h[1],h[2]))
        if default_hash == tmp[1]:
            sys.exit(1)
        
sys.exit(0)
