#!/usr/bin/perl

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use warnings;
use strict;
use JSON;
use NethServer::ApiTools;
use Convert::Base32;
use NethServer::Password;
use Sys::Hostname;

my $db = esmith::ConfigDB->open_ro;
my $input = NethServer::ApiTools::readInput();
my $username = $input->{'username'} || '';
my $OtpStatus;
my $key;
my $hostname = Sys::Hostname::hostname();
my $file;

if ( $username eq 'root') {
    $file = '/root/.2fa.secret';
} else {
    $file = "/var/lib/nethserver/home/$username/.2fa.secret";
}

if (! -f $file) {
    $key = `/usr/bin/openssl rand -hex 20`;
    $OtpStatus = 'disabled';
} else {
    if ( $username eq 'root') {
        $key = NethServer::Password->new('.2fa.secret',{'defaultDir' => '/root'})->getAscii();
    } else {
        $key = NethServer::Password->new('.2fa.secret',{'defaultDir' => '/var/lib/nethserver/home/$username'})->getAscii();
    }
    $OtpStatus = 'enabled';
}

## clean up
$key  =~ s/\R//g;

# we need to convert the hex token to binary base32 
my $secret = uc encode_base32( pack("H*", $key) );

# we need to find the PIN for single use (recovery)
open(FH, "/usr/bin/oathtool  -w 4 $key|");
my @ret;
while (<FH>) {
    chomp;
    my ($code) = split('\n');
    push(@ret, $code);
}

print encode_json ({"Key" => $key,"Secret"=> $secret,"Code"=> \@ret,"OtpStatus" => $OtpStatus,
    "Token" => "otpauth://totp/$username\@$hostname?secret=$secret"});
exit(0);
