#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

require '/usr/libexec/nethserver/api/lib/helper_functions.pl';

use esmith::ConfigDB;

my %hints = ();
my $out = `/usr/libexec/nethserver/api/system-settings/check-default-password`;

if ($? > 0 ) {
    $hints{'Password'} = 'change_default_root_password';
} 


my $db = esmith::ConfigDB->open_ro();
my $access = $db->get_prop('cockpit.socket', 'access') || '';
my $limit = $db->get_prop('cockpit.socket', 'LimitAccess') || '';

if ($access =~ /red/ && $limit eq '') {
    $hints{'LimitAccess'} = 'limit_red_access_by_ip';
}

hints('', \%hints, '');
