#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

. /usr/libexec/nethserver/api/lib/helper_functions

data=$(cat /dev/stdin)
action=$(echo $data | jq -r '.action')

function _get
{
    field=$1
    echo $data | jq -r ".$field"
}

case $action in

    "root")
        # convert array to comma-separated string
        mail=$(echo $data | jq -rc '.EmailAddress | map(tostring) | join(",")')
        /sbin/e-smith/config setprop root SenderAddress "$(_get SenderAddress)" KeepMessageCopy "$(_get KeepMessageCopy)" EmailAddress "$mail"
        /sbin/e-smith/signal-event -j notifications-save
        ;;

    "hints")
        /sbin/e-smith/config setprop cockpit.socket ShowHints "$(_get ShowHints)"
       ;;

    "cockpit")
        # convert array to comma-separated string
        limit=$(echo $data | jq -rc '.LimitAccess | map(tostring) | join(",")')
        /sbin/e-smith/config setprop cockpit.socket LimitAccess "$limit" access "$(_get access)"
        /sbin/e-smith/signal-event -j firewall-adjust
        ;;

    "smarthost")
        /sbin/e-smith/config setprop postfix SmartHostPassword "$(_get SmartHostPassword)" SmartHostPort "$(_get SmartHostPort)" \
            SmartHostTlsStatus "$(_get SmartHostTlsStatus)" SmartHostUsername "$(_get SmartHostUsername)" SmartHostName "$(_get SmartHostName)" SmartHostStatus "$(_get SmartHostStatus)"
        /sbin/e-smith/signal-event -j nethserver-mail-smarthost-save
        ;;

    "logrotate")
        /sbin/e-smith/config setprop logrotate Compression "$(_get Compression)" Rotate "$(_get Rotate)" Times "$(_get Times)"
        /sbin/e-smith/signal-event -j nethserver-base-update
        ;;

esac

if [ $? -gt 0 ]; then
    error "EventFailed" "See /var/log/messages"
else
    success
fi
