#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

. /usr/libexec/nethserver/api/lib/helper_functions

data=$(cat /dev/stdin)
action=$(echo $data | jq -r '.action')

function _get
{
    field=$1
    echo $data | jq -r ".$field"
}

case $action in

    "root")
        # convert array to comma-separated string
        mail=$(echo $data | jq -rc '.EmailAddress | map(tostring) | join(",")')
        /sbin/e-smith/config setprop root SenderAddress "$(_get SenderAddress)" KeepMessageCopy "$(_get KeepMessageCopy)" EmailAddress "$mail"
        /sbin/e-smith/signal-event -j notifications-save
        ;;

    "hints")
        /sbin/e-smith/config setprop cockpit.socket ShowHints "$(_get ShowHints)"
       ;;

    "cockpit")
        # convert array to comma-separated string
        limit=$(echo $data | jq -rc '.LimitAccess | map(tostring) | join(",")')
        /sbin/e-smith/config setprop cockpit.socket LimitAccess "$limit" access "$(_get access)"
        /sbin/e-smith/signal-event -j firewall-adjust
        ;;

    "user_settings_page")
        /sbin/e-smith/config setprop cockpit.socket UserSettingsPage "$(_get UserSettingsPage)" UserSettingsGrantAccess "$(_get UserSettingsGrantAccess)"
        /sbin/e-smith/expand-template /etc/httpd/conf.d/default-virtualhost.inc
        /sbin/e-smith/expand-template /etc/cockpit/cockpit.conf
        /usr/sbin/httpd -t && /usr/bin/systemctl reload httpd && /usr/bin/systemctl restart cockpit
        ;;

    "smarthost")
        /sbin/e-smith/config setprop postfix SmartHostPassword "$(_get SmartHostPassword)" SmartHostPort "$(_get SmartHostPort)" \
            SmartHostTlsStatus "$(_get SmartHostTlsStatus)" SmartHostUsername "$(_get SmartHostUsername)" SmartHostName "$(_get SmartHostName)" SmartHostStatus "$(_get SmartHostStatus)"
        /sbin/e-smith/signal-event -j nethserver-mail-smarthost-save
        ;;

    "logrotate")
        /sbin/e-smith/config setprop logrotate Compression "$(_get Compression)" Rotate "$(_get Rotate)" Times "$(_get Times)"
        /sbin/e-smith/signal-event -j nethserver-base-update
        ;;

    "shellPolicy")
        /sbin/e-smith/config setprop sssd ShellOverrideStatus "$(_get shellPolicy)"
        /sbin/e-smith/signal-event -j nethserver-sssd-save
        ;;

    "otp")
        OtpStatus=$(_get OtpStatus)
        OtpCockpit=$(_get OtpCockpit)
        OtpSshd=$(_get OtpSshd)
        username=$(_get username)
        Key=$(_get Key)
        secret_path=/var/lib/nethserver/home/$username/.2fa.secret
        secret_cockpit=/var/lib/nethserver/home/$username/.2fa_cockpit.secret
        secret_sshd=/var/lib/nethserver/home/$username/.2fa_sshd.secret

        if [[ $username = 'root' ]];then
            secret_path=/root/.2fa.secret
            secret_cockpit=/root/.2fa_cockpit.secret
            secret_sshd=/root/.2fa_sshd.secret
        fi

        if [[ $OtpStatus = 'enabled' ]];then
            /usr/bin/echo $Key > $secret_path
            /usr/bin/chmod 600 $secret_path

            if [[ $OtpCockpit = 'enabled' ]]; then 
                /usr/bin/ln -s $secret_path $secret_cockpit
            elif [[ $OtpCockpit = 'disabled' ]]; then 
                /usr/bin/rm -f $secret_cockpit
            fi

            if [[ $OtpSshd = 'enabled' ]]; then 
                /usr/bin/ln -s $secret_path $secret_sshd
            elif [[ $OtpSshd = 'disabled' ]]; then 
                /usr/bin/rm -f $secret_sshd
            fi
        elif [[ $OtpStatus = 'disabled' ]]; then
            /usr/bin/rm -f $secret_path
            /usr/bin/rm -f $secret_cockpit
            /usr/bin/rm -f $secret_sshd
        fi

        /usr/bin/sudo /sbin/e-smith/signal-event -j otp-save
        ;;


esac

if [ $? -gt 0 ]; then
    error "EventFailed" "See /var/log/messages"
else
    success
fi
