#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

require '/usr/libexec/nethserver/api/lib/helper_functions.pl';

use strict;
use warnings;

use esmith::NetworksDB;
use JSON;

my $db = esmith::NetworksDB->open_ro();
my $details;

foreach ($db->green()) {
    my $bootproto = $_->prop('bootproto') || 'none';
    if ($bootproto eq 'dhcp') {
        $details->{$_->key} = 'interface_must_be_static';
    }
}

my $out = `/usr/libexec/nethserver/eth-unmapped`;
if ($out && -f '/var/run/.nethserver-fixnetwork') {
    my $unmapped = decode_json($out);
    foreach (@$unmapped) {
        $details->{$_->{'name'}} = 'unmapped_interface_from_restore';
    }
}

if ($details) {
    hints(undef,$details);
} else {
    hints();
}
