#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use warnings;
use strict;
use JSON;
use esmith::ConfigDB;

my $ret;
my @records;

$ret->{'status'} = decode_json(`/usr/libexec/nethserver/trusted-networks`);

my $db = esmith::ConfigDB->open_ro('networks');
foreach ($db->get_all_by_prop('type' => 'network')) {
    my %props = $_->props;
    delete $props{'type'};
    my $r = { 'name' => $_->key, 'type' => 'network', 'props' => \%props };
    push(@records, $r);

}

$ret->{'configuration'} = \@records;

print encode_json($ret); 
