#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;

require '/usr/libexec/nethserver/api/lib/helper_functions.pl';

use JSON;
use esmith::db;
use esmith::ConfigDB;

my $db = esmith::db->open("configuration");
my $dbh = esmith::ConfigDB->open("hosts")   || esmith::ConfigDB->create('hosts');

our $out;

sub set_default {
    my $field = shift;
    my $default = shift;

    if ($out->{'configuration'}{'pki'}{'props'}{$field} eq '') {
        $out->{'configuration'}{'pki'}{'props'}{$field} = $default;
    }
}

my $input = readInput();
my $cmd = $input->{'action'};

# Check if input is not a pipe
if ($cmd eq 'list') {
    $out->{'status'} = '';
    my @certs;
    foreach my $crt (values decode_json(`/usr/libexec/nethserver/cert-list`)) {
        push(@certs, $crt);
    }
    $out->{'configuration'}{'certificates'} = \@certs;
    $out->{'configuration'}{'pki'} = $db->prepare_json('pki');

    set_default('CountryCode','--');
    set_default('State','SomeState');
    set_default('Locality','Hometown');
    set_default('Organization','Example');
    set_default('OrganizationalUnitName','Main');
    set_default('CommonName','NethServer');
    set_default('EmailAddress',"");
    set_default('SubjectAltName',$db->get_type('DomainName'));

    # Output all know  domains/FQDN of the server
    my @domains = ();

    foreach my $h ($dbh->get_all_by_prop('type'=>'self')) {
        my $domain = $h->key;
        push @domains, $domain;
    }

    push @domains, $db->get('SystemName').'.'.$db->get('DomainName'),$db->get('DomainName');
    my $domains = join (',',do { my %seen; grep { !$seen{$_}++ } @domains });

    $out->{'KnownDomains'} = $domains;

} elsif ($cmd eq 'info') {
    my $name = $input->{'name'};
    $out->{'certificate'} = `/usr/libexec/nethserver/pki-info -s $name | base64 -w 0`;
}


print encode_json($out);
