#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

data=$(cat /dev/stdin)
action=$(echo $data | jq -r '.action')

function _get
{
    field=$1
    echo $data | jq -r ".props.$field"
}

case $action in

    "self-signed")
        /sbin/e-smith/config setprop pki SubjectAltName "$(_get SubjectAltName)" State "$(_get State)" EmailAddress "$(_get EmailAddress)" \
            Organization "$(_get Organization)" CertificateDuration "$(_get CertificateDuration)" \
            Locality "$(_get Locality)" CommonName "$(_get CommonName)" \
            CountryCode "$(_get CountryCode)" OrganizationalUnitName "$(_get OrganizationalUnitName)" 
        /etc/e-smith/events/actions/nethserver-generate-certificate
        /sbin/e-smith/signal-event -j certificate-update
        ;;

    "set-default")
        /sbin/e-smith/config setprop pki KeyFile "$(_get KeyFile)" CrtFile "$(_get CrtFile)" ChainFile "$(_get ChainFile)"
        /sbin/e-smith/signal-event -j certificate-update
        ;;

    "upload")
       name=$(echo $data | jq -r '.files.name')
       crt=$(mktemp)
       echo $data | jq -r '.files.certificate' | base64 -d > $crt
       key=$(mktemp)
       echo $data | jq -r '.files.key' | base64 -d > $key
       chain=$(mktemp)
       echo $data | jq -r '.files.chain' | base64 -d > $chain
       /sbin/e-smith/signal-event -j certificate-upload "$name" "$crt" "$key" "$chain"
       rm -f "$crt" "$key" "$chain"
       ;;

    "lets-encrypt")
        /sbin/e-smith/config setprop pki LetsEncryptMail "$(_get LetsEncryptMail)" LetsEncryptDomains "$(_get LetsEncryptDomains)" LetsEncryptRenewDays "$(_get LetsEncryptRenewDays)"
        /usr/libexec/nethserver/letsencrypt-certs -f
        /sbin/e-smith/signal-event -j certificate-update
       ;;

esac
